### ISSUE TITLE
error with maximizing

### ISSUE THREAD

**Issue by orzklv** [phpusr/yandex-music-player#4]
![Screenshot from 2020-10-13 13-07-34](https://user-images.githubusercontent.com/54666588/95833589-45d68500-0d55-11eb-9863-4d577f2b4eda.png)

**Comment by orzklv** [comment]
pls creator sama can you add icons. there is no icons showing up on dock

**Comment by phpusr** [comment]
Yes, there is a problem with expanding to full screen, I will try to fix it when I have time. What do you mean by dock? Trey? Can you mark on the screenshot?

**Comment by iliman** [comment]
> What do you mean by dock? Trey? Can you mark on the screenshot?

@phpusr, icon appears in the overview but not in the dock (GNOME 40):

![image](https://user-images.githubusercontent.com/4136507/126041710-c4beb9c4-1e1b-47e3-8fab-3d516aa5a9a0.png)
![image](https://user-images.githubusercontent.com/4136507/126041517-873d74fc-921f-460d-aa82-a05484574639.png)

And if you add YMP to your favorites (pin to dock) and run it, it will open as a standalone app:
![image](https://user-images.githubusercontent.com/4136507/126042295-7c017ea1-067a-40fe-8265-1d3405d34a23.png)
