### ISSUE TITLE
Unable to open equalizer

### ISSUE THREAD

**Issue by ssstroke** [phpusr/yandex-music-player#6]
From the volume slider when I click on the EQ button the equalizer slides out, but then slides back, like if I were to press EQ button again to close it. It closes in about a second, but each time it changes a bit, usually it takes ~0.5 seconds. The equalizer, however, works, if I am able to click enable button fast enough while it's still opened.

Things I've tried: restarting application, maximizing/minimizing window, pausing tracks

OS: Arch Linux
Kernel: 5.16.16-arch1-1
Desktop environment: Plasma 5.24.3

**Comment by phpusr** [comment]
Fixed in [v1.4.1](https://github.com/phpusr/yandex-music-player/releases/tag/v1.4.1).

**Comment by ssstroke** [comment]
> Fixed in [v1.4.1](https://github.com/phpusr/yandex-music-player/releases/tag/v1.4.1).

Thank you ;)
