### ISSUE TITLE
Unable to open "Listeners" and "Likes"

### ISSUE THREAD

**Issue by ssstroke** [phpusr/yandex-music-player#8]
This issue is extremely similar to [this one](https://github.com/phpusr/yandex-music-player/issues/6) with EQ problem, but now I found it on "Artist" page in "Info" section.
When pressing a button in "Listeners in _month_" and "Likes in _month_" popup shows up for a brief moment and then pops back in.

**Comment by phpusr** [comment]
Can you send a screenshot or a link from the web version? I ca't find this page.

**Comment by ssstroke** [comment]
![Screenshot_20220504_072321](https://user-images.githubusercontent.com/85955834/166622997-6543adac-99fc-4e07-b8fc-8534b6d7775c.png)

**Comment by phpusr** [comment]
Fixed in [v1.4.2](https://github.com/phpusr/yandex-music-player/releases/tag/v1.4.2).
